version: '3.8'

services:
  laravel:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: objective-laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./code:/var/www/html
    networks:
      - objetive_network

  servidor:
    image: nginx:alpine
    container_name: objective-nginx
    restart: unless-stopped
    depends_on:
      - laravel
    ports:
      - "8001:80"
    volumes:
      - ./code/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - objetive_network
networks:
  objetive_network:
    driver: bridge